name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.1'
    - run: go get gotest.tools/gotestsum
    - run: gotestsum --junitfile junit.xml
    - uses: jinhong-/action-surefire-report@v1.0.2-hotfix2
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        report_paths: junit.xml
    - name: Run golangci-lint
      uses: actions-contrib/golangci-lint@v1